### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by TheBeachMaster** [Jcardif/Notice#1]
Did you have a look at [this](https://developer.xamarin.com/recipes/android/networking/detect-network-connection/) 
I guess you're using [this tutorial](http://www.c-sharpcorner.com/article/xamarin-android-create-android-application-to-check-network/) 

Have you verified that your app permissions to use internet are set?

**Comment by Jcardif** [comment]
I had not seen that yet... Lemme look at it.
Thanks a lot

**Comment by Jcardif** [comment]
Yup the permissions are enabled

**Comment by TheBeachMaster** [comment]
Let me know how it works out

**Comment by Jcardif** [comment]
` bool isOnline = (networkInfo!=null)&&networkInfo.IsConnected;
 is what was missing... Thanks it finally worked

**Comment by Jcardif** [comment]
` bool isOnline = (networkInfo!=null)&&networkInfo.IsConnected;`
this is what was missing. Finally it worked. Thanks
